# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 121a2702780d7c5fae281f5db9d520697aa07376a646d7d6faf6977ab4b0980b909e4afc2640903ba9106bbe1f06233772283b42b300acf87d90e465b5af24ea

test:
  secret_key_base: c9c1c94a143541752e0d9eee86790a75a7caef9b4edbaa89c6c08977f7ad956117a1de7619c195e779518a358b05b5653343b52abd3a91089af4c0237a48d8cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
